# Generated by Django 5.2.1 on 2025-06-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_is_email_verified'),
        ('products', '0003_alter_comment_parent_alter_comment_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='saved_products',
            field=models.ManyToManyField(related_name='saved_by_users', to='products.product'),
        ),
    ]
